// <auto-generated />
using HarvardUniversity.DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarvardUniversity.DataAccessLayer.Migrations
{
    [DbContext(typeof(HarvardUniversityContext))]
    [Migration("20241112211716_InitialCreateAzure")]
    partial class InitialCreateAzure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This mission is achieved through research to identify the social and behavioral determinants of health,\r\n                                        development and evaluation of interventions and policies leading to the improvement of population health,\r\n                                        and the preparation of professionals and researchers who will fill leadership positions in advocacy \r\n                                        and public service.",
                            Name = "Society, Human Development and Health"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science and engineering technology enterprises have a great demand for managers \r\n                                        who are not only skilled at business, but who also understand the principles underlying the science, technology, \r\n                                        and engineering ventures they must manage.",
                            Name = "Science, Technology and Management"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Through the Graduate School of Arts and Sciences, prospective students apply for \r\n                                        doctoral and master’s degree study at the Harvard John A. Paulson School of Engineering \r\n                                        and Applied Sciences (SEAS). These programs lie at the interfaces of engineering, \r\n                                        the applied sciences (from biology to physics), and technology.",
                            Name = "Engineering and Applied Sciences"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bioengineering is inherently interdisciplinary and combines faculty and research centers from across \r\n                                        our campuses and Harvard teaching hospitals.",
                            Name = "Bioengineering"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Applied Mathematics is an interdisciplinary field that focuses on the creation and imaginative \r\n                                        use of mathematical concepts to pose and solve problems over the entire gamut of the physical \r\n                                        and biomedical sciences and engineering, and increasingly, the social sciences and humanities.",
                            Name = "Applied Mathematics"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Prospective students apply through GSAS; in the online application, select “Engineering and \r\n                                        Applied Sciences” as your program choice and select 'PhD Computer Science' in the Area of Study menu.",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Data Science lies at the intersection of statistical methodology, computational science, and a wide range \r\n                                        of application domains. The program offers strong preparation in statistical modeling, machine learning, \r\n                                        optimization, management and analysis of massive data sets, and data acquisition.",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Electrical Engineering (EE) studies systems that sense, analyze, and interact with the world.\r\n                                        Electrical engineers invent devices for sensing and actuation, design physical substrates for \r\n                                        computation, create algorithms for analysis and control, and expand the theory of information \r\n                                        processing.",
                            Name = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Department of Near Eastern Languages and Civilizations (NELC) encompasses\r\n                                        the study of ancient and modern peoples, languages, literatures, cultures, \r\n                                        and societies of the Near and Middle East.",
                            Name = "Near Eastern Languages and Civilizations"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The PhD program in quantum science and engineering (QSE) lies at the interface of physics,\r\n                                        chemistry, and engineering, providing students with exciting opportunities to explore the fundamentals, realizations, \r\n                                        and applications of QSE.",
                            Name = "Quantum Science and Engineering"
                        });
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "SE-01"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            Name = "SE-02"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 8,
                            Name = "SE-08"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Name = "JB-01"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 6,
                            Name = "DC-23"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 7,
                            Name = "DE-15"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 5,
                            Name = "SX-02"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 9,
                            Name = "SX-02"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            Name = "FQ-14"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 4,
                            Name = "SR-01"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 6,
                            Name = "SM-03"
                        });
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Kirk",
                            GroupId = 1,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sheva",
                            GroupId = 5,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Smith",
                            GroupId = 9,
                            LastName = "Luke"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Marko",
                            GroupId = 11,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Snow",
                            GroupId = 11,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Jon",
                            GroupId = 1,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Alex",
                            GroupId = 10,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Luke",
                            GroupId = 11,
                            LastName = "Kane"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Alex",
                            GroupId = 2,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jon",
                            GroupId = 11,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Snow",
                            GroupId = 3,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Leo",
                            GroupId = 6,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Leo",
                            GroupId = 8,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Andrue",
                            GroupId = 7,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Messy",
                            GroupId = 5,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Kane",
                            GroupId = 3,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Sterling",
                            GroupId = 1,
                            LastName = "Sanchez"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Snow",
                            GroupId = 9,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Kane",
                            GroupId = 1,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Leo",
                            GroupId = 7,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Endy",
                            GroupId = 1,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Mark",
                            GroupId = 5,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Roberto",
                            GroupId = 9,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Kail",
                            GroupId = 2,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Sanchez",
                            GroupId = 8,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Smith",
                            GroupId = 1,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Homer",
                            GroupId = 5,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Endy",
                            GroupId = 5,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Joy",
                            GroupId = 4,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Mark",
                            GroupId = 3,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Marko",
                            GroupId = 11,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Mark",
                            GroupId = 6,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Snow",
                            GroupId = 3,
                            LastName = "Leo"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Leo",
                            GroupId = 9,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Sanchez",
                            GroupId = 8,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Kirk",
                            GroupId = 9,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Marge",
                            GroupId = 11,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Rick",
                            GroupId = 5,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Rick",
                            GroupId = 1,
                            LastName = "Kane"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Joy",
                            GroupId = 1,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Roberto",
                            GroupId = 11,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Kail",
                            GroupId = 3,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Andrue",
                            GroupId = 8,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Jane",
                            GroupId = 2,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Alex",
                            GroupId = 6,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Mark",
                            GroupId = 10,
                            LastName = "Luke"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Sterling",
                            GroupId = 3,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Sterling",
                            GroupId = 2,
                            LastName = "Jane"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Jon",
                            GroupId = 8,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Kirk",
                            GroupId = 10,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Luke",
                            GroupId = 10,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Snow",
                            GroupId = 1,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Marge",
                            GroupId = 9,
                            LastName = "Jane"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Kail",
                            GroupId = 7,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Sterling",
                            GroupId = 4,
                            LastName = "Sanchez"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Sanchez",
                            GroupId = 7,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Sterling",
                            GroupId = 1,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Alex",
                            GroupId = 2,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Marge",
                            GroupId = 11,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Rodrigez",
                            GroupId = 4,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Roberto",
                            GroupId = 11,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Kail",
                            GroupId = 1,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Andrue",
                            GroupId = 5,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Some",
                            GroupId = 2,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Snow",
                            GroupId = 3,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Jane",
                            GroupId = 9,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Luke",
                            GroupId = 10,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Kail",
                            GroupId = 1,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Kane",
                            GroupId = 8,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Marge",
                            GroupId = 7,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Alex",
                            GroupId = 9,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Sheva",
                            GroupId = 6,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Marko",
                            GroupId = 9,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Alex",
                            GroupId = 3,
                            LastName = "Leo"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Kirk",
                            GroupId = 11,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Joy",
                            GroupId = 5,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Jon",
                            GroupId = 8,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Marge",
                            GroupId = 9,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Endy",
                            GroupId = 10,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Smith",
                            GroupId = 10,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Sanchez",
                            GroupId = 11,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Homer",
                            GroupId = 6,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Jane",
                            GroupId = 2,
                            LastName = "Gary"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Jane",
                            GroupId = 8,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Sanchez",
                            GroupId = 6,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Andrue",
                            GroupId = 10,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Snow",
                            GroupId = 10,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Sanchez",
                            GroupId = 7,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Mark",
                            GroupId = 5,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Rick",
                            GroupId = 4,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Leo",
                            GroupId = 10,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Some",
                            GroupId = 3,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Messy",
                            GroupId = 9,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Marge",
                            GroupId = 1,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Gary",
                            GroupId = 8,
                            LastName = "Gary"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Andrue",
                            GroupId = 9,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Rodrigez",
                            GroupId = 3,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Joy",
                            GroupId = 6,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Snow",
                            GroupId = 2,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Luke",
                            GroupId = 1,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 101,
                            FirstName = "Rodrigez",
                            GroupId = 1,
                            LastName = "Luke"
                        },
                        new
                        {
                            Id = 102,
                            FirstName = "Messy",
                            GroupId = 1,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 103,
                            FirstName = "Kane",
                            GroupId = 6,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 104,
                            FirstName = "Rick",
                            GroupId = 7,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 105,
                            FirstName = "Jane",
                            GroupId = 3,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 106,
                            FirstName = "Kail",
                            GroupId = 1,
                            LastName = "Sanchez"
                        },
                        new
                        {
                            Id = 107,
                            FirstName = "Kail",
                            GroupId = 2,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 108,
                            FirstName = "Andrue",
                            GroupId = 1,
                            LastName = "Leo"
                        },
                        new
                        {
                            Id = 109,
                            FirstName = "Jon",
                            GroupId = 4,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 110,
                            FirstName = "Sterling",
                            GroupId = 1,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 111,
                            FirstName = "Kane",
                            GroupId = 7,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 112,
                            FirstName = "Kirk",
                            GroupId = 9,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 113,
                            FirstName = "Jane",
                            GroupId = 8,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 114,
                            FirstName = "Luke",
                            GroupId = 9,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 115,
                            FirstName = "Roberto",
                            GroupId = 6,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 116,
                            FirstName = "Rick",
                            GroupId = 2,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 117,
                            FirstName = "Andrue",
                            GroupId = 7,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 118,
                            FirstName = "Piter",
                            GroupId = 10,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 119,
                            FirstName = "Alex",
                            GroupId = 11,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 120,
                            FirstName = "Kail",
                            GroupId = 11,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 121,
                            FirstName = "Marge",
                            GroupId = 11,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 122,
                            FirstName = "Kirk",
                            GroupId = 4,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 123,
                            FirstName = "Rodrigez",
                            GroupId = 1,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 124,
                            FirstName = "Marko",
                            GroupId = 6,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 125,
                            FirstName = "Piter",
                            GroupId = 1,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 126,
                            FirstName = "Jon",
                            GroupId = 7,
                            LastName = "Andrue"
                        },
                        new
                        {
                            Id = 127,
                            FirstName = "Marge",
                            GroupId = 7,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 128,
                            FirstName = "Alex",
                            GroupId = 10,
                            LastName = "Gary"
                        },
                        new
                        {
                            Id = 129,
                            FirstName = "Snow",
                            GroupId = 11,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 130,
                            FirstName = "Messy",
                            GroupId = 11,
                            LastName = "Mark"
                        },
                        new
                        {
                            Id = 131,
                            FirstName = "Smith",
                            GroupId = 4,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 132,
                            FirstName = "Snow",
                            GroupId = 5,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 133,
                            FirstName = "Endy",
                            GroupId = 10,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 134,
                            FirstName = "Piter",
                            GroupId = 2,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 135,
                            FirstName = "Jane",
                            GroupId = 6,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 136,
                            FirstName = "Rick",
                            GroupId = 10,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 137,
                            FirstName = "Some",
                            GroupId = 10,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 138,
                            FirstName = "Sterling",
                            GroupId = 3,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 139,
                            FirstName = "Messy",
                            GroupId = 8,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 140,
                            FirstName = "Messy",
                            GroupId = 9,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 141,
                            FirstName = "Sterling",
                            GroupId = 5,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 142,
                            FirstName = "Kane",
                            GroupId = 10,
                            LastName = "Luke"
                        },
                        new
                        {
                            Id = 143,
                            FirstName = "Gary",
                            GroupId = 11,
                            LastName = "Snow"
                        },
                        new
                        {
                            Id = 144,
                            FirstName = "Messy",
                            GroupId = 9,
                            LastName = "Roberto"
                        },
                        new
                        {
                            Id = 145,
                            FirstName = "Jane",
                            GroupId = 10,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 146,
                            FirstName = "Leo",
                            GroupId = 1,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 147,
                            FirstName = "Mark",
                            GroupId = 9,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 148,
                            FirstName = "Gary",
                            GroupId = 2,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 149,
                            FirstName = "Rick",
                            GroupId = 7,
                            LastName = "Jane"
                        },
                        new
                        {
                            Id = 150,
                            FirstName = "Kane",
                            GroupId = 3,
                            LastName = "Gary"
                        },
                        new
                        {
                            Id = 151,
                            FirstName = "Messy",
                            GroupId = 3,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 152,
                            FirstName = "Jon",
                            GroupId = 1,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 153,
                            FirstName = "Rodrigez",
                            GroupId = 2,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 154,
                            FirstName = "Sanchez",
                            GroupId = 4,
                            LastName = "Jane"
                        },
                        new
                        {
                            Id = 155,
                            FirstName = "Sterling",
                            GroupId = 3,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 156,
                            FirstName = "Andrue",
                            GroupId = 4,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 157,
                            FirstName = "Smith",
                            GroupId = 4,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 158,
                            FirstName = "Andrue",
                            GroupId = 6,
                            LastName = "Marko"
                        },
                        new
                        {
                            Id = 159,
                            FirstName = "Mark",
                            GroupId = 10,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 160,
                            FirstName = "Leo",
                            GroupId = 11,
                            LastName = "Alex"
                        },
                        new
                        {
                            Id = 161,
                            FirstName = "Jon",
                            GroupId = 2,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 162,
                            FirstName = "Kane",
                            GroupId = 11,
                            LastName = "Marko"
                        },
                        new
                        {
                            Id = 163,
                            FirstName = "Andrue",
                            GroupId = 4,
                            LastName = "Luke"
                        },
                        new
                        {
                            Id = 164,
                            FirstName = "Homer",
                            GroupId = 11,
                            LastName = "Endy"
                        },
                        new
                        {
                            Id = 165,
                            FirstName = "Homer",
                            GroupId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 166,
                            FirstName = "Marko",
                            GroupId = 4,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 167,
                            FirstName = "Endy",
                            GroupId = 10,
                            LastName = "Gary"
                        },
                        new
                        {
                            Id = 168,
                            FirstName = "Endy",
                            GroupId = 9,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 169,
                            FirstName = "Some",
                            GroupId = 11,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 170,
                            FirstName = "Alex",
                            GroupId = 3,
                            LastName = "Sheva"
                        },
                        new
                        {
                            Id = 171,
                            FirstName = "Some",
                            GroupId = 6,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 172,
                            FirstName = "Marge",
                            GroupId = 1,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 173,
                            FirstName = "Leo",
                            GroupId = 10,
                            LastName = "Leo"
                        },
                        new
                        {
                            Id = 174,
                            FirstName = "Gary",
                            GroupId = 2,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 175,
                            FirstName = "Sheva",
                            GroupId = 11,
                            LastName = "Sanchez"
                        },
                        new
                        {
                            Id = 176,
                            FirstName = "Roberto",
                            GroupId = 9,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 177,
                            FirstName = "Jon",
                            GroupId = 2,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 178,
                            FirstName = "Messy",
                            GroupId = 4,
                            LastName = "Homer"
                        },
                        new
                        {
                            Id = 179,
                            FirstName = "Snow",
                            GroupId = 9,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 180,
                            FirstName = "Jane",
                            GroupId = 11,
                            LastName = "Rick"
                        },
                        new
                        {
                            Id = 181,
                            FirstName = "Sheva",
                            GroupId = 1,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 182,
                            FirstName = "Mark",
                            GroupId = 6,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 183,
                            FirstName = "Gary",
                            GroupId = 5,
                            LastName = "Piter"
                        },
                        new
                        {
                            Id = 184,
                            FirstName = "Sanchez",
                            GroupId = 2,
                            LastName = "Some"
                        },
                        new
                        {
                            Id = 185,
                            FirstName = "Kail",
                            GroupId = 8,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 186,
                            FirstName = "Piter",
                            GroupId = 10,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 187,
                            FirstName = "Endy",
                            GroupId = 8,
                            LastName = "Leo"
                        },
                        new
                        {
                            Id = 188,
                            FirstName = "Luke",
                            GroupId = 10,
                            LastName = "Kail"
                        },
                        new
                        {
                            Id = 189,
                            FirstName = "Sheva",
                            GroupId = 6,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 190,
                            FirstName = "Sheva",
                            GroupId = 4,
                            LastName = "Joy"
                        },
                        new
                        {
                            Id = 191,
                            FirstName = "Smith",
                            GroupId = 6,
                            LastName = "Marge"
                        },
                        new
                        {
                            Id = 192,
                            FirstName = "Marge",
                            GroupId = 11,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 193,
                            FirstName = "Gary",
                            GroupId = 1,
                            LastName = "Jon"
                        },
                        new
                        {
                            Id = 194,
                            FirstName = "Piter",
                            GroupId = 2,
                            LastName = "Kirk"
                        },
                        new
                        {
                            Id = 195,
                            FirstName = "Rodrigez",
                            GroupId = 7,
                            LastName = "Jane"
                        },
                        new
                        {
                            Id = 196,
                            FirstName = "Marge",
                            GroupId = 4,
                            LastName = "Sterling"
                        },
                        new
                        {
                            Id = 197,
                            FirstName = "Kail",
                            GroupId = 10,
                            LastName = "Rodrigez"
                        },
                        new
                        {
                            Id = 198,
                            FirstName = "Rick",
                            GroupId = 3,
                            LastName = "Sanchez"
                        },
                        new
                        {
                            Id = 199,
                            FirstName = "Endy",
                            GroupId = 8,
                            LastName = "Messy"
                        },
                        new
                        {
                            Id = 200,
                            FirstName = "Sterling",
                            GroupId = 10,
                            LastName = "Endy"
                        });
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Group", b =>
                {
                    b.HasOne("HarvardUniversity.DataAccessLayer.Models.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Student", b =>
                {
                    b.HasOne("HarvardUniversity.DataAccessLayer.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HarvardUniversity.DataAccessLayer.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
